apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: soundcheck-backend
  description: Service wrapping the Soundcheck backend of the Spotify Plugins for Backstage (SP4B) commercial bundle.
  annotations:
    github.com/project-slug: soundcheck/soundcheck-backend
    backstage.io/source-location: url:https://ghe.spotify.net/soundcheck/soundcheck-backend/tree/master
  namespace: default
spec:
  owner: toast-infra
  type: service
  system: soundcheck
  lifecycle: production
